# -*- mode: python -*-
# Be awayre this code was mainly generated by an LLM!
"""Module to build NixOS configurations across different architectures.

This script determines the architecture of various hosts in the flake and builds their
system configurations either locally or remotely on a management server.
"""

import os
import socket
import subprocess
import sys
from pathlib import Path


def get_hosts(devenv_root: str) -> list[str]:
    """Get the list of hostnames from the specified Nix flake.

    Args:
        devenv_root: The path to the flake root.

    Returns:
        A list of hostnames.
    """
    expr = f"{devenv_root}#nixosConfigurations"
    apply_expr = 'pkgs: builtins.concatStringsSep " " (builtins.attrNames pkgs)'
    cmd = ["nix", "eval", expr, "--apply", apply_expr]
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as error:
        print(error.stderr)
        sys.exit(error.returncode)
    hosts_str = result.stdout.strip().strip('"')
    return hosts_str.split()


def get_architecture(devenv_root: str, host: str) -> str:
    """Determine the system architecture for a specific host.

    Args:
        devenv_root: The path to the flake root.
        host: The hostname to check.

    Returns:
        The system architecture string (e.g., 'x86_64-linux').
    """
    expr = f"{devenv_root}#nixosConfigurations.{host}.pkgs.system"
    cmd = ["nix", "eval", expr]
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as error:
        print(error.stderr)
        sys.exit(error.returncode)
    return result.stdout.strip().strip('"')


def build_on_management(devenv_root: str, host: str) -> str:
    """Perform a dry-run build of a host's configuration on the management server.

    Args:
        devenv_root: The path to the flake root.
        host: The hostname to build.

    Returns:
        An empty string.
    """
    print(f"Building {host} on management")
    expr = f"{devenv_root}#nixosConfigurations.{host}.config.system.build.toplevel"
    cmd = ["nix", "build", "--dry-run", expr]
    subprocess.run(cmd, check=True, timeout=1800)
    return ""  # nix doesn't print paths unless specified, path handled outside


def build_remotely_on_management(devenv_root: str, host: str) -> str:
    """Build a host's configuration remotely using a management server as a builder.

    Args:
        devenv_root: The path to the flake root.
        host: The hostname to build.

    Returns:
        The store path of the built toplevel.
    """
    print(f"Building {host} remotely on management")
    expr = f"{devenv_root}#nixosConfigurations.{host}.config.system.build.toplevel"
    cmd = [
        "nix",
        "build",
        expr,
        "--eval-store",
        "auto",
        "--store",
        "ssh-ng://management.int.zweili.org",
        "--no-link",
        "--print-out-paths",
    ]
    try:
        result = subprocess.run(
            cmd, check=True, capture_output=True, text=True, timeout=1800
        )
    except subprocess.CalledProcessError as error:
        print(error.stderr)
        sys.exit(error.returncode)
    return result.stdout.strip()


def build_locally(devenv_root: str, host: str) -> str:
    """Perform a dry-run build of a host's configuration locally.

    Args:
        devenv_root: The path to the flake root.
        host: The hostname to build.

    Returns:
        An empty string.
    """
    print(f"Building {host} locally")
    expr = f"{devenv_root}#nixosConfigurations.{host}.config.system.build.toplevel"
    cmd = ["nix", "build", "--dry-run", expr]
    subprocess.run(cmd, check=True, timeout=3600)
    print()
    return ""


def main() -> None:
    """Main entry point to build all hosts based on architecture and current machine."""
    devenv_root: str = os.environ["DEVENV_ROOT"]
    builds_directory: Path = Path.home() / "builds"
    builds_directory.mkdir(parents=True, exist_ok=True)

    hostname: str = socket.gethostname()

    skip: list[str] = []
    hosts: list[str] = get_hosts(devenv_root)

    for host in hosts:
        if host in skip:
            continue
        print(host)

        architecture: str = get_architecture(devenv_root, host)

        if hostname == "management" and architecture == "aarch64-linux":
            build_on_management(devenv_root, host)
        elif hostname != "management" and architecture == "aarch64-linux":
            build_remotely_on_management(devenv_root, host)
        elif hostname != "management" and architecture == "x86_64-linux":
            build_locally(devenv_root, host)
        else:
            print(f"Skipping: {host}\n")
            continue


if __name__ == "__main__":
    main()
