{ ... }:
{
  imports = [
    ./common
    ./common-x86
    ./data-share
    ./docker
    ./email
    ./eog
    ./hunspell
    ./libimobiledevice
    ./lockscreen
    ./logs-share
    ./log-to-ram
    ./makemkv
    ./nix-direnv
    ./pipewire
    ./rdp
    ./restic-client-desktop
    ./scripts
    ./steam
    ./syslog
    ./telegram-notifications
    ./tlp
    ./tmux
    ./username
    ./virtualbox-guest
    ./profiles/desktop
  ];
}
