[tool.mypy]
strict = true

[tool.ruff]
line-length = 88
indent-width = 4
exclude = [
  "scripts/*.sh",
  "scripts/test-build",
]
include = [
  "scripts/*",
]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint]
fixable = ["ALL"]
select = [ "ALL" ]

[tool.ruff.lint.isort]
force-single-line = true
