#+title: NixOS Configuration

This repository lives on https://git.zweili.org/. Due to agressive LLM
crawlers I had to make it private there. If you want to collaborate you
can contact me through email or Mastodon.

This repository contains my configuration for my Nixos systems. I don't
provide any garantuees that it will work on other systems. In addition
some of the scripts required for installation will destroy your data
when used.

* Installation
** x86_64-linux without disko

1. Boot the installation ISO.
2. Format the disk with the following script
   =sudo ./scripts/format-disk.sh=. Make sure to edit it beforehand, to
   point it to the correct disk.
3. Next install the system with
   =sudo nixos-install --no-root-passwd --root /mnt/nixos --impure --flake .#SYSTEMNAME --no-channel-copy=
4. Rename the partitions with the script
   =sudo ./scripts/rename-partitions.sh=. With this script as well.
   Check that you're pointing to the correct disk.

When everything is finished you can reboot the system and remove the USB
stick. You have now a fully encrypted NixOS system.

** Additional script

- If you only want to prepare an SD card with an UEFI partition for a
  Raspberry Pi 4 you can use the script =sudo ./scripts/create-uefi.sh=.
  This is currently outdated and not needed for SD cards formatted with
  disko. But it might be needed for systems that don't have the UEFI
  parition on the same device.

** Non-Nixos System

#+begin_src bash
./scripts/install-home-manager.sh
#+end_src
