{ ... }:
{
  imports = [
    ./common
    ./programs/alacritty
    ./programs/ansible
    ./programs/calibre
    ./programs/czkawka
    ./programs/emacs
    ./programs/email
    ./programs/evince
    ./programs/fzf
    ./programs/git
    ./programs/hunspell
    ./programs/keeweb
    ./programs/mpv
    ./programs/open-port
    ./programs/rapid-photo-downloader
    ./programs/signal
    ./programs/ssh
    ./programs/starship
    ./programs/telegram
    ./programs/tmux
    ./programs/work-desktop
    ./programs/yt-dlp
    ./services/desktop-base
    ./services/dunst
    ./services/espanso
    ./services/grobi
  ];
}
