{ inputs, ... }:
{
  imports = [
    inputs.agenix.homeManagerModules.default
    ./common
    ./programs/ansible
    ./programs/beets
    ./programs/calibre
    ./programs/czkawka
    ./programs/emacs
    ./programs/email
    ./programs/evince
    ./programs/fzf
    ./programs/git
    ./programs/hunspell
    ./programs/keeweb
    ./programs/mpv
    ./programs/open-port
    ./programs/rapid-photo-downloader
    ./programs/signal
    ./programs/ssh
    ./programs/starship
    ./programs/telegram
    ./programs/tmux
    ./programs/work-desktop
    ./programs/yt-dlp
    ./services/desktop-base
    ./services/dunst
    ./services/espanso
    ./services/grobi
    ./services/xcompose
    ./services/xidlehook
  ];
}
