;; basic settings
(load-file (modules-path "az_detect_os.el"))
(load-file (modules-path "az_packages.el"))
;; keybindings
(load-file (modules-path "az_evil.el"))
(load-file (modules-path "az_hydra.el"))
(load-file (modules-path "az_keybindings.el"))

(load-file (modules-path "az_dired.el"))
(load-file (modules-path "az_theme.el"))
(load-file (modules-path "az_ui.el"))
(load-file (modules-path "az_utils.el"))
(load-file (modules-path "az_various.el"))
(load-file (modules-path "az_window_split.el"))
(load-file (modules-path "az_xclip.el"))

;; note taking and writing
(load-file (modules-path "az_deft_raw.el"))
(load-file (modules-path "az_deft.el"))
(load-file (modules-path "az_denote.el"))
(load-file (modules-path "az_langtool.el"))
(load-file (modules-path "az_markdown.el"))
(load-file (modules-path "az_move_text.el"))
(load-file (modules-path "az_olivetti.el"))
(load-file (modules-path "az_org.el"))
(load-file (modules-path "az_org_insert.el"))
(load-file (modules-path "az_pdf_tools.el"))
(load-file (modules-path "az_spellcheck.el"))

;; programming
(load-file (modules-path "az_annotate.el"))
(load-file (modules-path "az_company.el"))
(load-file (modules-path "az_copilot.el"))
(load-file (modules-path "az_direnv.el"))
(load-file (modules-path "az_format_all.el"))
(load-file (modules-path "az_flycheck.el"))
(load-file (modules-path "az_languageserver.el"))
(load-file (modules-path "az_magit.el"))
(load-file (modules-path "az_nix.el"))
(load-file (modules-path "az_powershell.el"))
(load-file (modules-path "az_projectile.el"))
(load-file (modules-path "az_python.el"))
(load-file (modules-path "az_webmode.el"))
(load-file (modules-path "az_yaml.el"))

;; various third party
(load-file (modules-path "az_counsel.el"))
(load-file (modules-path "az_counsel-git-grep-current-mode.el"))
(load-file (modules-path "az_keyring_update.el"))
(load-file (modules-path "az_journalctl.el"))
(load-file (modules-path "az_manuals.el"))
(load-file (modules-path "az_mu4e.el"))
(load-file (modules-path "az_treemacs.el"))
(load-file (modules-path "az_perspective.el"))
(load-file (modules-path "az_vterm.el"))
(load-file (modules-path "az_yasnippet.el"))
