;;(setq disable-fringe t)
;;(setq enable-color-theme t)
;;(setq enable-email t)
;;(setq enable-emojis t)
;;(setq enable-font t)
;;(setq enable-lantool t)
;;(setq enable-pdf-tools t)
;;(setq enable-scroll-bar t)
