#!/usr/bin/env bash
set -e

builds_directory="$HOME"/builds
hosts=($(echo $(nix eval "$DEVENV_ROOT"#nixosConfigurations --apply 'pkgs: builtins.concatStringsSep " " (builtins.attrNames pkgs)') | xargs))
skip=(
    "desktop-vm"
    "gwyn"
    "loki-test"
    "mobile"
    "staubfinger"
)
timestamp=$(date -u +"%Y%m%d")
mkdir -p "$builds_directory"
for host in "${hosts[@]}"; do
    build_path="$builds_directory/$timestamp-$host"
    # shellcheck disable=SC2076
    if [[ " ${skip[*]} " =~ " ${host} " ]]; then
        continue
    fi
    echo "$host"
    nixos-rebuild build --flake "$DEVENV_ROOT#${host}"
    if [ ! "$(hostname)" = "management" ]; then
        upload-to-cache ./result
        rsync --links result "$USER"@mangement.2li.local:$build_path"
    fi
    rm -f "$build_path"
    mv result "$build_path"
    echo
    echo
done
