#!/usr/bin/env bash
set -e

hosts=($(echo $(nix eval "$DEVENV_ROOT"#nixosConfigurations --apply 'pkgs: builtins.concatStringsSep " " (builtins.attrNames pkgs)') | xargs))
skip=(
    "desktop-vm"
    "gwyn"
    "loki-test"
    "mobile"
    "staubfinger"
)
timestamp=$(date -u +"%Y%m%d")
mkdir -p builds
for host in "${hosts[@]}"; do
    # shellcheck disable=SC2076
    if [[ " ${skip[*]} " =~ " ${host} " ]]; then
        continue
    fi
    echo "$host"
    nixos-rebuild build --flake "$DEVENV_ROOT#${host}"
    if [ ! "$(hostname)" = "management" ]; then
        upload-to-cache ./result
    fi
    rm -f builds/"$timestamp-$host"
    mv result builds/"$timestamp-$host"
    echo
    echo
done
