#!/usr/bin/env bash
set -e

builds_directory="$HOME"/builds
hosts=($(echo $(nix eval "$DEVENV_ROOT"#nixosConfigurations --apply 'pkgs: builtins.concatStringsSep " " (builtins.attrNames pkgs)') | xargs))
skip=(
    "desktop-vm"
    "loki-test"
    "mobile"
)
timestamp=$(date -u +"%Y%m%d")

mkdir -p "$builds_directory"
for host in "${hosts[@]}"; do
    build_path="$builds_directory/$timestamp-$host"
    # shellcheck disable=SC2076
    if [[ " ${skip[*]} " =~ " ${host} " ]]; then
        continue
    fi

    # skip architectures we can't build
    architecture=$(nix eval "$DEVENV_ROOT"#nixosConfigurations."$host".pkgs.system)
    if [ "$(hostname)" = "management" ] && [ "$architecture" = '"aarch64-linux"' ]; then
        echo "Building $host on management"
        store_path=$(nix build "$DEVENV_ROOT#nixosConfigurations.${host}.config.system.build.toplevel")
    elif [ ! "$(hostname)" = "management" ] && [ "$architecture" = '"aarch64-linux"' ]; then
        echo "Building $host remotely on management"
        store_path=$(nix build "$DEVENV_ROOT#nixosConfigurations.${host}.config.system.build.toplevel" \
            --eval-store auto \
            --store ssh-ng://management.2li.local \
            --no-link \
            --print-out-paths)
    elif [ ! "$(hostname)" = "management" ] && [ "$architecture" = '"x86_64-linux"' ]; then
        echo "Building $host locally"
        store_path=$(nix build "$DEVENV_ROOT#nixosConfigurations.${host}.config.system.build.toplevel" --no-link --print-out-paths)
        upload-to-cache "$store_path"
        echo
    else
        echo "Skipping: $host"
        echo ""
        continue
    fi
    echo "Create symlink for $store_path at $build_path"
    ssh -t "$USER"@management.2li.local "ln -sfn $store_path $build_path"
    echo
    echo
done
