#!/usr/bin/env bash
set -e

hosts=($(echo $(nix eval "$DEVENV_ROOT"#nixosConfigurations --apply 'pkgs: builtins.concatStringsSep " " (builtins.attrNames pkgs)') | xargs))
skip=(
    "desktop-vm"
    "gwyn"
    "loki-test"
    "mobile"
    "test-raspi"
    "staubfinger"
)

for host in "${hosts[@]}"; do
    if [[ " ${skip[*]} " =~ " ${host} " ]]; then
        continue
    fi
    echo $host
    nixos-rebuild dry-build --flake $DEVENV_ROOT#${host}
    echo
    echo
done
