#!/usr/bin/env -S nix shell .#pkgs.python3 --command python
# -*- mode: python -*-

import argparse
import logging
import os
import subprocess
from pathlib import Path


def main() -> None:
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)

    rsa_key: Path = Path("~/.nixos/secrets/ssh_keys/ansible/ansible.key").expanduser()
    os.environ["NIX_SSHOPTS"] = f"-i {rsa_key}"

    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description="Remote NixOS deployment tool",
    )
    parser.add_argument("host", help="Target hostname")
    parser.add_argument(
        "-r",
        "--reboot",
        action="store_true",
        help="Reboot the host after boot deployment",
    )
    args: argparse.Namespace = parser.parse_args()

    host: str = args.host
    fqdn: str = f"{host}.vpn.zweili.org"
    subcommand: str = "boot" if args.reboot else "switch"

    logger.info("%s via %s", fqdn, subcommand)
    subprocess.run(
        [
            "nixos-rebuild-ng",
            subcommand,
            "-j",
            "auto",
            "--sudo",
            "--target-host",
            fqdn,
            "--flake",
            f".#{host}",
        ],
        check=True,
    )


if __name__ == "__main__":
    main()
