#!/usr/bin/env bash

set -e

cd /home/andreas/.nixos

hosts=($(echo $(nix eval .#nixosConfigurations --apply 'pkgs: builtins.concatStringsSep " " (builtins.attrNames pkgs)') | xargs))
skip=(
    "desktop-vm"
    "capricorn"
    "gwyn"
    "loki-test"
    "mobile"
    "staubfinger"
    "test-raspi"
)

rsa_key="$HOME/.nixos/secrets/ssh_keys/ansible/ansible.key"
export NIX_SSHOPTS="-i $rsa_key"
reboot=0

while getopts ":r" option; do
    case $option in
    r)
        reboot=1
        ;;
    esac
done

for host in "${hosts[@]}"; do
    # Check if the host is in the skip list
    if [[ " ${skip[*]} " =~ " ${host} " ]]; then
        continue
    fi
    fqdn="$host.2li.local"
    if [ $reboot -eq 0 ]; then
        echo $fqdn
        nixos-rebuild-ng switch -j auto --sudo --target-host $fqdn --flake ".#$host"
    else
        if [[ "$(hostname)" == "$host" ]]; then
            echo "Skip management"
            continue
        fi
        if [ "$host" = "management" ]; then
            echo "Skip cache"
            echo ""
            continue
        fi
        nixos-rebuild-ng boot -j auto --sudo --target-host $fqdn --flake ".#$host"
        echo "build $host"
        ssh -i $rsa_key $fqdn 'sudo reboot'
    fi
    echo
    echo
done
if [ $reboot -eq 1 ]; then
    # rebuild and restart the management server at the end
    host="management"
    fqdn="$host.2li.local"
    echo "build $host"
    nixos-rebuild-ng boot -j auto --sudo --target-host $fqdn --flake ".#$host"
    ssh -i $rsa_key $fqdn 'sudo reboot'
fi
