#+title: Capricorn
#+date: [2024-12-12 Thu 20:03]
#+identifier: 20241212T200348
#+author: Andreas Zweili

* Todos
** NEXT Fix webcam
:LOGBOOK:
- State "WAITING"    from "NEXT"       [2025-02-15 Sat 14:53]
:END:

Seems to be a firmware bug.
- https://github.com/NixOS/nixpkgs/issues/225743

- Other issue tracking this issue and probably more relevant than the NixOS issue.

**[2025-11-03]**

There have been some updates in the thread I should try out.

** NEXT Enable kanata

It's a software that lets you remap keyboard keys.
With this I can enable home-row mods on my notebook keyboard which would be really helpful on the go as it is a bit of a hassle to use the Voyager for short sessions.

https://github.com/jtroo/kanata/tree/main

- [X] Map home row keys to the win, alt, shift and ctrl
  https://github.com/jtroo/kanata/blob/main/docs/simulated_output/sim.kbd
- [ ] Hold Space, enable arrow keys on HKJL

** NEXT Fix hibernation

Not really a high priority.

[[https://github.com/lovesegfault/nix-config/blob/ff964c6f11010942e56bd73a6c4766dffdd3e031/hardware/thinkpad-z13.nix#L123][nix-config/hardware/thinkpad-z13.nix at ff964c6f11010942e56bd73a6c4766dffdd3e031 · lovesegfault/nix-config]]

[[https://www.kernel.org/doc/html/v5.4/power/basic-pm-debugging.html][Debugging hibernation and suspend — The Linux Kernel documentation]]

** NEXT Implement BTRFS autoScrub

https://search.nixos.org/options?channel=25.05&show=services.btrfs.autoScrub.enable&query=btrfs+autoScrub


** Features to add
:PROPERTIES:
:VISIBILITY: folded
:END:

The following tasks enable certain hardware features that I currently don't have on any of my hardware.
Namely face unlock and the finger print reader.

*** WAITING [#C] [[https://github.com/boltgolt/howdy][boltgolt/howdy: 🛡️ Windows Hello™ style facial authentication for Linux]]
:LOGBOOK:
- State "WAITING"    from "TODO"       [2025-03-31 Mon 17:11]
:END:

2025-03-31
KDE currently doesn't have support for face unlocking.

Since the webcam doesn't work I don't really have to bother with this for the moment.

https://github.com/search?q=lang%3ANix+AND+NOT+repo%3ANixOS%2Fnixpkgs+howdy&type=code

* Footnotes

[fn:3] https://github.com/fairyglade/ly/pull/654
[fn:2] https://kernelnewbies.org/Linux_6.13
[fn:1] https://wiki.archlinux.org/title/Intel_graphics#Crash/freeze_on_low_power_Intel_CPUs
