# Be awayre this code was mainly generated by an LLM!

import argparse
import subprocess
import sys
from pathlib import Path


def sync_non_flacs_to_target(source: Path, target: Path) -> None:
    print("Sync files")
    subprocess.run(
        [
            "rsync",
            "--delete",
            "--human-readable",
            "--inplace",
            "--recursive",
            "--size-only",
            "--stats",
            "--verbose",
            "--exclue='*.flac'",
            str(source),
            str(target),
        ],
        check=True,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync playlist files and cover art to target location",
    )
    parser.add_argument(
        "target",
        type=Path,
        help="Top-level destination directory (will sync to <destination>/synced)",
    )
    music_dir = Path.home() / "Music"
    parser.add_argument(
        "source",
        type=Path,
        default=music_dir,
        help="Source directory (default: ~/Music)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    source: Path = args.source.resolve()
    target: Path = args.destination.resolve()

    Path.mkdir(target, exist_ok=True)
    sync_non_flacs_to_target(source, target)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(1)
