[Automation]
verify_file=false

[Device]
device_autodetection=true
this_computer_path=
this_computer_source=false

[DidYouKnowWindow]
windowSize=@Size(570 350)

[Display]
did_you_know_index=9
did_you_know_on_startup=false
ignore_unhandled_file_exts=TMP, DAT
survey_countdown=0
survey_taken=2026

[ErrorLog]
visible=false
windowPosition=@Point(0 0)
windowSize=@Size(320 240)

[MainWindow]
centerSplitterSizes=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x3\0\0\x1(\0\0\x2S\0\0\x1(\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
leftPanelSplitterSizes=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xec\0\0\0\xfa\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
maximized=true
proximityButtonPressed=true
rightButtonPressed=0
rightPanelSplitterSizes=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x2J\0\0\x1\x8c\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
sourceButtonPressed=true
windowPosition=@Point(0 0)
windowSize=@Size(3840 2088)

[Performance]
generate_thumbnails=true
keep_thumbnails_days=30
save_fdo_thumbnails=true
use_thumbnail_cache=true

[Presets]
preset_photo_rename\1\name=Zweili Default Photos
preset_photo_rename\1\pref_list=Date time, Image date, YYYYMMDD, Text, T, , Date time, Image date, HHMMSS, Text, _, , Sequences, Downloads today, Three digits
preset_photo_rename\size=1
preset_photo_subfolder\1\name=Zweili Default Photo
preset_photo_subfolder\1\pref_list=Date time, Image date, YYYY, /, , , Date time, Image date, YYYYMMDD, Text, T000000, 
preset_photo_subfolder\2\name=Zweili Default
preset_photo_subfolder\2\pref_list=Date time, Image date, YYYY, /, , , Date time, Image date, MM, Text, -, , Date time, Image date, DD
preset_photo_subfolder\size=2
preset_video_rename\1\name=Zweili Default Videos
preset_video_rename\1\pref_list=Date time, Video date, YYYYMMDD, Text, T, , Date time, Video date, HHMMSS, Text, _, , Sequences, Downloads today, Three digits
preset_video_rename\size=1
preset_video_subfolder\1\name=Zweili Default Video
preset_video_subfolder\1\pref_list=Date time, Video date, YYYY, /, , , Date time, Video date, YYYYMMDD, Text, T000000, 
preset_video_subfolder\2\name=Zweili Default
preset_video_subfolder\2\pref_list=Date time, Video date, YYYY, /, , , Date time, Video date, MM, Text, -, , Date time, Video date, DD
preset_video_subfolder\size=2

[Program]
program_version=0.9.36

[Rename]
downloads_today=2026-01-20, 50
photo_download_folder=/home/andreas/nextcloud/20_pictures
photo_rename=Date time, Image date, YYYYMMDD, Text, T, , Date time, Image date, HHMMSS, Text, _, , Sequences, Downloads today, Three digits
photo_subfolder=Date time, Image date, YYYY, /, , , Date time, Image date, MM, Text, -, , Date time, Image date, DD
stored_sequence_no=10
synchronize_raw_jpg=true
video_download_folder=/home/andreas/nextcloud/20_pictures
video_rename=Date time, Video date, YYYYMMDD, Text, T, , Date time, Video date, HHMMSS, Text, _, , Sequences, Downloads today, Three digits
video_subfolder=Date time, Video date, YYYY, /, , , Date time, Video date, MM, Text, -, , Date time, Video date, DD
